data:
  settings_file:
    path: settings-data.yaml
  input:
    path: dataset-small.csv
    separator: '$'
  extraction:
    function:
      path: extraction
  output:
    file:
      name: results
      separator: ','
  splitting:
    runs: 10
    folding:
      method: KFOLD
      number: 2
      seeds:
        from_list: [1,2,3,4,5,6,7,8,9,10]
        from_file: